services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
      TZ: America/Sao_Paulo
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app

  adminer:
    environment:
      TZ: America/Sao_Paulo
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - app

volumes:
  db:

networks:
  app:
    driver: bridge
